// Generated by gencpp from file testbot_lab2/myjintResponse.msg
// DO NOT EDIT!


#ifndef TESTBOT_LAB2_MESSAGE_MYJINTRESPONSE_H
#define TESTBOT_LAB2_MESSAGE_MYJINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace testbot_lab2
{
template <class ContainerAllocator>
struct myjintResponse_
{
  typedef myjintResponse_<ContainerAllocator> Type;

  myjintResponse_()
    : status()  {
    }
  myjintResponse_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::testbot_lab2::myjintResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::testbot_lab2::myjintResponse_<ContainerAllocator> const> ConstPtr;

}; // struct myjintResponse_

typedef ::testbot_lab2::myjintResponse_<std::allocator<void> > myjintResponse;

typedef boost::shared_ptr< ::testbot_lab2::myjintResponse > myjintResponsePtr;
typedef boost::shared_ptr< ::testbot_lab2::myjintResponse const> myjintResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::testbot_lab2::myjintResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::testbot_lab2::myjintResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace testbot_lab2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::testbot_lab2::myjintResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::testbot_lab2::myjintResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testbot_lab2::myjintResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testbot_lab2::myjintResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testbot_lab2::myjintResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testbot_lab2::myjintResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::testbot_lab2::myjintResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::testbot_lab2::myjintResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::testbot_lab2::myjintResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "testbot_lab2/myjintResponse";
  }

  static const char* value(const ::testbot_lab2::myjintResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::testbot_lab2::myjintResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status\n"
;
  }

  static const char* value(const ::testbot_lab2::myjintResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::testbot_lab2::myjintResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myjintResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::testbot_lab2::myjintResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::testbot_lab2::myjintResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESTBOT_LAB2_MESSAGE_MYJINTRESPONSE_H
