// Generated by gencpp from file testbot_lab2/myjint.msg
// DO NOT EDIT!


#ifndef TESTBOT_LAB2_MESSAGE_MYJINT_H
#define TESTBOT_LAB2_MESSAGE_MYJINT_H

#include <ros/service_traits.h>


#include <testbot_lab2/myjintRequest.h>
#include <testbot_lab2/myjintResponse.h>


namespace testbot_lab2
{

struct myjint
{

typedef myjintRequest Request;
typedef myjintResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct myjint
} // namespace testbot_lab2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::testbot_lab2::myjint > {
  static const char* value()
  {
    return "3217da37e7b93e31d3fd5f2778f26983";
  }

  static const char* value(const ::testbot_lab2::myjint&) { return value(); }
};

template<>
struct DataType< ::testbot_lab2::myjint > {
  static const char* value()
  {
    return "testbot_lab2/myjint";
  }

  static const char* value(const ::testbot_lab2::myjint&) { return value(); }
};


// service_traits::MD5Sum< ::testbot_lab2::myjintRequest> should match 
// service_traits::MD5Sum< ::testbot_lab2::myjint > 
template<>
struct MD5Sum< ::testbot_lab2::myjintRequest>
{
  static const char* value()
  {
    return MD5Sum< ::testbot_lab2::myjint >::value();
  }
  static const char* value(const ::testbot_lab2::myjintRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::testbot_lab2::myjintRequest> should match 
// service_traits::DataType< ::testbot_lab2::myjint > 
template<>
struct DataType< ::testbot_lab2::myjintRequest>
{
  static const char* value()
  {
    return DataType< ::testbot_lab2::myjint >::value();
  }
  static const char* value(const ::testbot_lab2::myjintRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::testbot_lab2::myjintResponse> should match 
// service_traits::MD5Sum< ::testbot_lab2::myjint > 
template<>
struct MD5Sum< ::testbot_lab2::myjintResponse>
{
  static const char* value()
  {
    return MD5Sum< ::testbot_lab2::myjint >::value();
  }
  static const char* value(const ::testbot_lab2::myjintResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::testbot_lab2::myjintResponse> should match 
// service_traits::DataType< ::testbot_lab2::myjint > 
template<>
struct DataType< ::testbot_lab2::myjintResponse>
{
  static const char* value()
  {
    return DataType< ::testbot_lab2::myjint >::value();
  }
  static const char* value(const ::testbot_lab2::myjintResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTBOT_LAB2_MESSAGE_MYJINT_H
