// Generated by gencpp from file testbot_lab2/myoint.msg
// DO NOT EDIT!


#ifndef TESTBOT_LAB2_MESSAGE_MYOINT_H
#define TESTBOT_LAB2_MESSAGE_MYOINT_H

#include <ros/service_traits.h>


#include <testbot_lab2/myointRequest.h>
#include <testbot_lab2/myointResponse.h>


namespace testbot_lab2
{

struct myoint
{

typedef myointRequest Request;
typedef myointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct myoint
} // namespace testbot_lab2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::testbot_lab2::myoint > {
  static const char* value()
  {
    return "77bf4dc6349a8d26f822ba0f0ed91793";
  }

  static const char* value(const ::testbot_lab2::myoint&) { return value(); }
};

template<>
struct DataType< ::testbot_lab2::myoint > {
  static const char* value()
  {
    return "testbot_lab2/myoint";
  }

  static const char* value(const ::testbot_lab2::myoint&) { return value(); }
};


// service_traits::MD5Sum< ::testbot_lab2::myointRequest> should match 
// service_traits::MD5Sum< ::testbot_lab2::myoint > 
template<>
struct MD5Sum< ::testbot_lab2::myointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::testbot_lab2::myoint >::value();
  }
  static const char* value(const ::testbot_lab2::myointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::testbot_lab2::myointRequest> should match 
// service_traits::DataType< ::testbot_lab2::myoint > 
template<>
struct DataType< ::testbot_lab2::myointRequest>
{
  static const char* value()
  {
    return DataType< ::testbot_lab2::myoint >::value();
  }
  static const char* value(const ::testbot_lab2::myointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::testbot_lab2::myointResponse> should match 
// service_traits::MD5Sum< ::testbot_lab2::myoint > 
template<>
struct MD5Sum< ::testbot_lab2::myointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::testbot_lab2::myoint >::value();
  }
  static const char* value(const ::testbot_lab2::myointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::testbot_lab2::myointResponse> should match 
// service_traits::DataType< ::testbot_lab2::myoint > 
template<>
struct DataType< ::testbot_lab2::myointResponse>
{
  static const char* value()
  {
    return DataType< ::testbot_lab2::myoint >::value();
  }
  static const char* value(const ::testbot_lab2::myointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTBOT_LAB2_MESSAGE_MYOINT_H
