// Generated by gencpp from file testbot_lab2/oint_control_srv.msg
// DO NOT EDIT!


#ifndef TESTBOT_LAB2_MESSAGE_OINT_CONTROL_SRV_H
#define TESTBOT_LAB2_MESSAGE_OINT_CONTROL_SRV_H

#include <ros/service_traits.h>


#include <testbot_lab2/oint_control_srvRequest.h>
#include <testbot_lab2/oint_control_srvResponse.h>


namespace testbot_lab2
{

struct oint_control_srv
{

typedef oint_control_srvRequest Request;
typedef oint_control_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct oint_control_srv
} // namespace testbot_lab2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::testbot_lab2::oint_control_srv > {
  static const char* value()
  {
    return "77bf4dc6349a8d26f822ba0f0ed91793";
  }

  static const char* value(const ::testbot_lab2::oint_control_srv&) { return value(); }
};

template<>
struct DataType< ::testbot_lab2::oint_control_srv > {
  static const char* value()
  {
    return "testbot_lab2/oint_control_srv";
  }

  static const char* value(const ::testbot_lab2::oint_control_srv&) { return value(); }
};


// service_traits::MD5Sum< ::testbot_lab2::oint_control_srvRequest> should match 
// service_traits::MD5Sum< ::testbot_lab2::oint_control_srv > 
template<>
struct MD5Sum< ::testbot_lab2::oint_control_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::testbot_lab2::oint_control_srv >::value();
  }
  static const char* value(const ::testbot_lab2::oint_control_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::testbot_lab2::oint_control_srvRequest> should match 
// service_traits::DataType< ::testbot_lab2::oint_control_srv > 
template<>
struct DataType< ::testbot_lab2::oint_control_srvRequest>
{
  static const char* value()
  {
    return DataType< ::testbot_lab2::oint_control_srv >::value();
  }
  static const char* value(const ::testbot_lab2::oint_control_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::testbot_lab2::oint_control_srvResponse> should match 
// service_traits::MD5Sum< ::testbot_lab2::oint_control_srv > 
template<>
struct MD5Sum< ::testbot_lab2::oint_control_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::testbot_lab2::oint_control_srv >::value();
  }
  static const char* value(const ::testbot_lab2::oint_control_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::testbot_lab2::oint_control_srvResponse> should match 
// service_traits::DataType< ::testbot_lab2::oint_control_srv > 
template<>
struct DataType< ::testbot_lab2::oint_control_srvResponse>
{
  static const char* value()
  {
    return DataType< ::testbot_lab2::oint_control_srv >::value();
  }
  static const char* value(const ::testbot_lab2::oint_control_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTBOT_LAB2_MESSAGE_OINT_CONTROL_SRV_H
