(cl:defpackage testbot_lab2-srv
  (:use )
  (:export
   "JINT_CONTROL_SRV"
   "<JINT_CONTROL_SRV-REQUEST>"
   "JINT_CONTROL_SRV-REQUEST"
   "<JINT_CONTROL_SRV-RESPONSE>"
   "JINT_CONTROL_SRV-RESPONSE"
   "MYJINT"
   "<MYJINT-REQUEST>"
   "MYJINT-REQUEST"
   "<MYJINT-RESPONSE>"
   "MYJINT-RESPONSE"
   "MYOINT"
   "<MYOINT-REQUEST>"
   "MYOINT-REQUEST"
   "<MYOINT-RESPONSE>"
   "MYOINT-RESPONSE"
   "OINT_CONTROL_SRV"
   "<OINT_CONTROL_SRV-REQUEST>"
   "OINT_CONTROL_SRV-REQUEST"
   "<OINT_CONTROL_SRV-RESPONSE>"
   "OINT_CONTROL_SRV-RESPONSE"
  ))

